---
name: github
provider: github.com
repository: docker-shellcheck
url: https://github.com/cardboardci/docker-shellcheck
clone:
  ssh: git@github.com:cardboardci/docker-shellcheck.git
  https: https://github.com/cardboardci/docker-shellcheck.git